Repository emqx/MQTTX, pull requests merged in 2020-07, with the labels that each got.

#258 style(errorTip): nowrap input error tip
  src/assets/scss/element/element-reset.scss
  src/lang/connections.ts
Labels: UI \ UX

#260 refactor(types): improve type definition
  src/components/SubscriptionsList.vue
  src/types/global.d.ts
  src/views/connections/ConnectionsDetail.vue
Labels: enhancement

#261 fix(publish): fix the issue that the payload of hex and base64 is a s…
  src/assets/scss/element/element-reset.scss
  src/components/MsgPublish.vue
  src/views/connections/ConnectionsDetail.vue
Labels: fix

#264 chore(package): change version to v1.3.2
  package.json
  src/main/updateChecker.ts
  src/views/about/index.vue
Labels: upgrade

#267 chore(package): revert vue-cli-plugin-electron-builder
  package.json
  yarn.lock
Labels: dependencies

#268 Develop
  yarn.lock
Labels: dependencies

#275 fix(getFiles): error prompt when SSL verification fails to read the file
  src/assets/scss/element/element-reset.scss
  src/utils/getFiles.ts
Labels: fix

#276 fix(connections): fixed messages duplicated
  src/store/modules/app.ts
  src/views/connections/ConnectionsDetail.vue
Labels: fix

#277 chore(package): change version to v1.3.3
  package.json
  src/main/updateChecker.ts
  src/views/about/index.vue
Labels: upgrade

#278 fix(connections): add remove message listener method
  src/views/connections/ConnectionsDetail.vue
  src/views/connections/index.vue
Labels: bug

#279 fix(getFiles): error prompt when SSL verification fails to read the file
  src/views/connections/ConnectionsDetail.vue
Labels: enhancement

#280 fix(getFiles): error prompt when SSL verification fails to read the file
  src/components/MsgLeftItem.vue
  src/components/MsgRightItem.vue
  src/views/connections/ConnectionsDetail.vue
Labels: feature

#281 fix(connections): fix can't remove listeners
  src/views/connections/ConnectionsDetail.vue
Labels: bug
