Repository emqx/MQTTX, pull requests merged in 2020-10, with the labels that each got.

#312 feat(connection): add export data menu
  src/lang/connections.ts
  src/views/connections/ConnectionsDetail.vue
Labels: feature

#315 feat(connection): add export data method
  src/background.ts
  src/components/ExportData.vue
  src/lang/common.ts
  src/main/saveFile.ts
  src/utils/exportData.ts
  src/views/connections/ConnectionsDetail.vue
Labels: feature

#318 feat(connection): change upload icon
  src/views/connections/ConnectionsDetail.vue
  src/views/settings/index.vue
Labels: refactor

#319 Improved translation content
  src/lang/about.ts
  src/lang/common.ts
  src/lang/connections.ts
  src/lang/settings.ts
Labels: enhancement

#320 fix(common): improve format
  src/components/ImportData.vue
  src/lang/common.ts
  src/views/settings/index.vue
Labels: enhancement

#322 chore(package): v1.3.3 -> v1.3.4
  package.json
  src/main/updateChecker.ts
  src/views/about/index.vue
Labels: enhancement

#324 feat(search): add multipleSearch function
  docs/manual-cn.md
  docs/manual.md
  src/lang/connections.ts
  src/main/getMenuTemplate.ts
  src/utils/matchMultipleSearch.ts
  src/views/connections/ConnectionsDetail.vue
Labels: feature

#325 docs(manual): update manual
  assets/mqttx-advance.png
  assets/mqttx-connection.png
  assets/mqttx-search.png
  assets/mqttx-theme.png
  assets/mqttx-topic-alias.png
  assets/mqttx-topic.png
  docs/manual-cn.md
  docs/manual.md
Labels: docs

#329 fix(ConnectionsDetail.vue): fix new message scroll bug when search
  src/views/connections/ConnectionsDetail.vue
Labels: bug

#330 feat(index.html): add loading page when load app
  public/index.html
Labels: enhancement

#336 refactor(ExportData.vue): add tips when no data is exported & format …
  src/components/ExportData.vue
Labels: refactor

#337 chore(husky): add pre-commit code format
  package.json
  yarn.lock
Labels: dependencies

#338 feat(tips): add some error tips when importData
  src/components/ExportData.vue
  src/components/ImportData.vue
  src/lang/connections.ts
Labels: enhancement

#339 feat(excel): new excel format for import and export data
  package.json
  src/background.ts
  src/components/ExportData.vue
  src/components/ImportData.vue
  src/main/saveExcel.ts
  yarn.lock
Labels: feature

#340 fix(subs): add trim function to topic & alias
  src/components/SubscriptionsList.vue
Labels: bug
