Repository emqx/MQTTX, pull requests merged in 2020-06, with the labels that each got.

#234 feat(connection): panel collapse to join status management
  src/assets/scss/element/element-reset.scss
  src/store/getter.ts
  src/store/modules/app.ts
  src/types/global.d.ts
  src/views/connections/ConnectionForm.vue
  src/views/connections/ConnectionInfo.vue
Labels: enhancement

#235 refactor(connection): rename to connections detail
  src/views/connections/ConnectionsDetail.vue
  src/views/connections/index.vue
Labels: refactor

#236 perf(postcss): add purgecss plugin
  package.json
  postcss.config.js
  vue.config.js
  yarn.lock
Labels: performance

#238 style(messages): modify the style of the message box
  src/assets/scss/element/element-reset.scss
  src/assets/scss/theme/dark.scss
  src/assets/scss/theme/light.scss
  src/assets/scss/theme/night.scss
  src/components/SubscriptionsList.vue
  src/views/connections/ConnectionsDetail.vue
Labels: UI \ UX

#239 chore(mqtt): upgrade mqtt.js & optimization error message
  package.json
  src/views/connections/ConnectionsDetail.vue
  yarn.lock
Labels: enhancement

#240 refactor(connection): disable disconnect button when disconnected
  src/views/connections/ConnectionsDetail.vue
  src/views/settings/index.vue
Labels: enhancement

#242 style(mqtt): fix code lint
  src/lang/connections.ts
  src/utils/mqttUtils.ts
  src/views/connections/ConnectionForm.vue
Labels: fix

#243 fix(mqttUtils): fix types errors
  src/utils/mqttUtils.ts
  src/views/connections/types.ts
Labels: fix

#244 fix(types.ts): change payloadFormatIndicator type to boolean
  src/views/connections/types.ts
Labels: fix

#246 docs(manual): update manual
  docs/manual-cn.md
Labels: docs

#248 fix(connections): add deep merge method to adapt old data
  src/utils/deepMerge.ts
  src/views/connections/ConnectionForm.vue
Labels: enhancement

#249 fix(ConnectionForm.vue): change label and willPayload fontSize
  src/components/MsgPublish.vue
  src/components/ResizeHeight.vue
  src/lang/connections.ts
  src/views/connections/ConnectionForm.vue
Labels: fix

#253 fix(ConnectionForm.vue): make name changeable and add nameTip
  src/lang/connections.ts
  src/views/connections/ConnectionForm.vue
Labels: enhancement

#254 fix(ConnectionInfo.vue): make name only and add verify
  src/views/connections/ConnectionInfo.vue
  src/views/connections/ConnectionsDetail.vue
Labels: bug

#256 refactor(request): reduce loadConnections request
  src/store/getter.ts
  src/store/modules/app.ts
  src/types/global.d.ts
  src/views/connections/ConnectionForm.vue
  src/views/connections/ConnectionInfo.vue
  src/views/connections/index.vue
Labels: refactor

#257 style(element): fix some style problems
  src/assets/scss/element/element-reset.scss
  src/components/MyDialog.vue
  src/views/connections/ConnectionForm.vue
Labels: UI \ UX
