Repository emqx/MQTTX, pull requests merged in 2020-12, with the labels that each got.

#395 chore(package): remove purge css package
  package.json
  postcss.config.js
  yarn.lock
Labels: dependencies

#397 feat(script): add api of the script
  src/api/script.ts
  src/lang/common.ts
  src/lang/script.ts
  src/utils/sandbox.ts
  src/views/script/index.vue
  src/views/script/types.ts
Labels: feature

#398 docs(manual): update contact information
  assets/emqx_wx.jpeg
  docs/manual-cn.md
Labels: docs

#400 refactor(types): replace require to import
  src/components/ExportData.vue
  src/types/shims-vue.d.ts
Labels: refactor

#405 chore(package): v1.4.1 -> v1.4.2
  package.json
  src/main/updateChecker.ts
  src/views/about/index.vue
Labels: upgrade

#406 fix(connections): fix can not init payload editor
  src/background.ts
  src/components/Editor.vue
  src/components/MsgLeftItem.vue
  src/components/MsgPublish.vue
  src/lang/script.ts
  src/types/global.d.ts
  src/views/connections/ConnectionsDetail.vue
  src/views/connections/index.vue
Labels: fix

#408 fix(connections): adjust icon style for 'ConnectionInfo.vue'
  src/views/connections/ConnectionForm.vue
  src/views/connections/ConnectionInfo.vue
Labels: UI \ UX

#410 additional word translation
  src/lang/common.ts
  src/lang/script.ts
Labels: enhancement

#411 fix(connections): fix the unread message count is NaN problem
  src/store/modules/app.ts
  src/views/connections/ConnectionsList.vue
Labels: fix

#412 feat(messageList): added pull-up & loading function to messageList & …
  src/components/MessageList.vue
  src/views/connections/ConnectionsDetail.vue
Labels: enhancement

#414 fix(messageList): fix the animation of adding a message
  src/components/MessageList.vue
  src/components/MyDialog.vue
  src/views/connections/ConnectionsDetail.vue
Labels: fix

#415 fix(msgList): fix showMessages value when has search conditions
  src/components/MessageList.vue
  src/views/connections/ConnectionsDetail.vue
Labels: fix

#416 feat(script): add route to script page on connection page
  src/components/UseScript.vue
Labels: enhancement

#419 docs(readme): update mqttx preview image
  assets/mqttx-preview.png
Labels: docs

#418 fix(msgList): split showMsgs when received much msgs in one second
  src/components/MessageList.vue
Labels: fix

#420 fix(connections): fix setMessageListHeight of undefined
  src/views/connections/index.vue
Labels: fix

#409 feature(connections): disable ConnectionInfo table editing when client was connected
  src/views/connections/ConnectionInfo.vue
Labels: enhancement

#421 docs(manual): update manual
  assets/mqttx-script.png
  docs/manual-cn.md
  docs/manual.md
Labels: docs

#417 refactor(subscriptions): optimize the error message when subscribing to $SYS fails
  src/components/SubscriptionsList.vue
  src/lang/connections.ts
  src/views/connections/types.ts
Labels: enhancement

#435 docs(issue): add bug report issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: discussion, docs, enhancement
