Repository emqx/MQTTX, pull requests merged in 2020-11, with the labels that each got.

#345 chore(package): upgrad dependencies
  package.json
  src/views/about/index.vue
  src/views/connections/ConnectionsDetail.vue
  yarn.lock
Labels: dependencies

#346 chore(package): v1.3.4 -> v1.4.0
  package.json
  src/main/updateChecker.ts
  src/views/about/index.vue
Labels: upgrade

#347 fix(router): fix router redirect error
  package.json
  src/components/Leftbar.vue
  src/router/routes.ts
  yarn.lock
Labels: bug

#348 fix(router): fix uncaught navigation duplicated
  src/router/index.ts
Labels: fix

#349 feat(window): add new window component
  src/assets/scss/connections.scss
  src/background.ts
  src/components/Leftbar.vue
  src/database/index.ts
  src/lang/common.ts
  src/main/newWindow.ts
  src/router/routes.ts
  src/views/connections/ConnectionsDetail.vue
  src/views/connections/ConnectionsList.vue
  src/views/connections/index.vue
  src/views/window/Window.vue
Labels: feature

#351 feat(connection): Support multi-window view messages
  src/background.ts
  src/main/newWindow.ts
  src/utils/api/connection.ts
  src/views/connections/ConnectionsDetail.vue
Labels: feature

#353 feat(i18n): Japanese translation
  src/lang/common.ts
  src/lang/connections.ts
Labels: enhancement

#356 fix(mqtt): fix mqtt version
  package.json
  yarn.lock
Labels: bug

#359 docs(manual): update manual
  assets/mqttx-muti-window.png
  docs/manual-cn.md
  docs/manual.md
Labels: docs

#362 feat(connection): add message count display when client connected
  src/assets/scss/element/element-reset.scss
  src/lang/connections.ts
  src/utils/element.ts
  src/views/connections/ConnectionsDetail.vue
Labels: feature

#363 refactor(connection): optimized code
  src/views/connections/ConnectionsDetail.vue
Labels: refactor

#364 refactor(messages): set dynamic height for messages list
  package.json
  src/assets/scss/base.scss
  src/components/MsgLeftItem.vue
  src/components/MsgPublish.vue
  src/components/MsgRightItem.vue
  src/types/shims-vue.d.ts
  src/views/connections/ConnectionsDetail.vue
  yarn.lock
Labels: refactor

#365 fix(connections): fix some types
  src/components/MsgLeftItem.vue
  src/views/connections/ConnectionsDetail.vue
Labels: fix

#369 style(MsgPublish.vue): change disabled style
  src/assets/scss/element/element-reset.scss
  src/components/MsgPublish.vue
  src/lang/connections.ts
Labels: UI \ UX

#371 Add readme Japanese translation
  README-CN.md
  README-JP.md
  README.md
Labels: docs

#372 Add manual Japanese translation
  assets/jp/mqttx-advance.png
  assets/jp/mqttx-brokerinfo.png
  assets/jp/mqttx-certs.png
  assets/jp/mqttx-connection.png
  assets/jp/mqttx-create.png
  assets/jp/mqttx-gif.gif
  assets/jp/mqttx-main.png
  assets/jp/mqttx-message.png
  assets/jp/mqttx-muti-window.png
  assets/jp/mqttx-search.png
  assets/jp/mqttx-theme.png
  assets/jp/mqttx-topic-alias.png
  assets/jp/mqttx-topic.png
  assets/jp/mqttx-update.png
  assets/jp/mqttx-user.png
  assets/jp/mqttx-v5.png
  assets/jp/mqttx-willmessage.png
  docs/manual-jp.md
Labels: docs

#374 japanese translation improvement
  src/lang/common.ts
  src/lang/connections.ts
Labels: enhancement

#377 feat(connection): add system info in bytes statistics
  src/lang/common.ts
Labels: fix

#380 fxi(ConnectionsDetail.vue): init sendFrequency when clearInterval
  src/views/connections/ConnectionsDetail.vue
Labels: fix

#381 chore(package): v1.4.0 -> v1.4.1
  package.json
  src/main/updateChecker.ts
  src/views/about/index.vue
Labels: upgrade

#383 refactor(api): refactor the directory structure c40a430
  src/api/connection.ts
  src/api/setting.ts
  src/background.ts
  src/components/ExportData.vue
  src/components/ImportData.vue
  src/components/SubscriptionsList.vue
  src/router/index.ts
  src/store/modules/app.ts
  src/views/connections/ConnectionForm.vue
  src/views/connections/ConnectionInfo.vue
  src/views/connections/ConnectionsDetail.vue
  src/views/connections/index.vue
  src/views/window/Window.vue
Labels: refactor

#384 fix(connections): fix stop send timed message error
  src/views/connections/index.vue
Labels: fix

#385 docs(manual): update manual
  assets/mqttx-bytes.png
  assets/mqttx-connection.png
  assets/mqttx-search.png
  assets/mqttx-window.png
  docs/manual-cn.md
  docs/manual.md
Labels: docs

#386 docs(manual): update manual
  assets/mqttx-timed-message.png
  docs/manual-cn.md
  docs/manual.md
  src/lang/common.ts
Labels: docs

#387 feat(lang): japanese translation
  src/lang/common.ts
  src/lang/connections.ts
Labels: enhancement

#391 fix(timeMsg): stopTimer when topic is null or publish failed
  src/views/connections/ConnectionsDetail.vue
Labels: fix
