Repository emqx/MQTTX, pull requests merged in 2021-06, with the labels that each got.

#587 fix(msg): fix cannot read property payloadType of undefined
  src/components/MsgPublish.vue
Labels: fix

#589 fix(msg): remove unused component & modify some styles
  src/assets/scss/element/element-reset.scss
  src/components/MsgPublish.vue
  src/utils/element.ts
Labels: UI \ UX, enhancement

#597 fix(deps): Upgrade MQTT.js to v4.2.6 to fix reconnect bug
  package.json
  yarn.lock
Labels: dependencies

#602 fix(msg): fix can not resize the editor
  src/components/MsgPublish.vue
  src/components/SubscriptionsList.vue
  src/lang/about.ts
  src/lang/common.ts
  src/lang/connections.ts
  src/lang/settings.ts
Labels: fix

#603 feat(config): add rpm & deb package
  package.json
  vue.config.js
Labels: Chore

#606 fix(config): fix console warning aboout websocket connect
  vue.config.js
Labels: fix

#609 feat(connection): auto focus on new collection input
  src/views/connections/ConnectionsList.vue
Labels: enhancement

#613 refactor(about): update copyright
  src/views/about/index.vue
Labels: UI \ UX, refactor
