Repository emqx/MQTTX, pull requests merged in 2021-05, with the labels that each got.

#554 fix(MsgPublish): support remove duplicates for payload & headers
  src/components/MsgPublish.vue
  src/utils/mqttUtils.ts
Labels: enhancement

#556 fix(connectionList): fix connection & collection tree sequence issue
  src/api/connection.ts
  src/components/MsgPublish.vue
  src/utils/connections.ts
  src/views/connections/ConnectionsList.vue
  src/views/connections/types.ts
Labels: feature, fix

#559 feat(settings): support remove history suggestion data
  package.json
  src/api/connection.ts
  src/components/ClearUpHistoryData.vue
  src/components/MsgPublish.vue
  src/database/index.ts
  src/lang/connections.ts
  src/lang/settings.ts
  src/views/settings/index.vue
Labels: feature

#560 fix(connectionsList): fix connection lists theme color issue
  src/views/connections/ConnectionsList.vue
Labels: UI \ UX, fix

#561 docs(medium): modify medium account link
  src/components/ClearUpHistoryData.vue
  src/views/settings/index.vue
Labels: fix

#563 fix(MsgPublish): fix publish history message index issue
  src/components/MsgPublish.vue
  src/views/connections/ConnectionsDetail.vue
Labels: fix

#565 chore(package): v1.5.3 -> v1.5.4
  src/main/updateChecker.ts
  src/views/about/index.vue
Labels: upgrade

#566 docs(readme): update cn to zh
  .github/CONTRIBUTING_CN.md
  README-CN.md
  docs/manual-cn.md
  src/components/Leftbar.vue
Labels: docs

#575 fix(msg): fix payload type can not restored
  src/components/MsgPublish.vue
Labels: fix

#578 chore(deps): bump vue-cli-plugin-electron-builder from 1.4.6 to 2.0.0
  package.json
  vue.config.js
  yarn.lock
Labels: dependencies
