Repository emqx/MQTTX, pull requests merged in 2021-09, with the labels that each got.

#676 fix(collection): enhance collection allow drop condition
  src/views/connections/ConnectionsList.vue
Labels: feature, fix

#679 fix(connectionDetail): fix connection detail scroll issue
  src/views/connections/ConnectionForm.vue
  src/views/connections/ConnectionsDetail.vue
  src/views/script/index.vue
Labels: fix

#680 fix(message): removed message ipc services
  src/background.ts
  src/views/connections/ConnectionsDetail.vue
Labels: fix

#681 fix(collection): remove/add collection trigger reload events
  src/utils/SystemTopicUtils.ts
  src/utils/convertPayload.ts
  src/utils/getClientId.ts
  src/utils/getCollectionId.ts
  src/utils/matchMultipleSearch.ts
  src/utils/time.ts
  src/utils/topicMatch.ts
  src/views/connections/ConnectionsDetail.vue
  src/views/connections/ConnectionsList.vue
Labels: fix

#683 fix(subscription): fix subscription remove failed issue
  src/components/SubscriptionsList.vue
  src/database/services/CollectionService.ts
  src/database/services/ConnectionService.ts
  src/views/connections/ConnectionsDetail.vue
Labels: bug

#685 feat(messages): ⚡ improve message list performence
  package.json
  src/components/MessageList.vue
  src/main.ts
  src/types/shims-vue.d.ts
  yarn.lock
Labels: feature, refactor

#686 docs(readme): fix slack badge
  README-CN.md
  README-JP.md
  README.md
Labels: fix, docs

#691 fix(message): fix leftItem color bar display issue
  src/components/MessageList.vue
Labels: bug

#692 doc(readme): update tech stack
  README-CN.md
  README-JP.md
  README.md
Labels: docs

#693 fix(message): fix service empty array query issue
  src/components/ExportData.vue
  src/components/UseScript.vue
  src/database/services/MessageService.ts
  src/utils/time.ts
  src/views/connections/ConnectionsList.vue
  src/views/script/index.vue
Labels: refactor

#694 fix(messageItem): fix left message item data state render issue
  src/components/MessageList.vue
  src/components/MsgLeftItem.vue
  src/types/global.d.ts
Labels: fix

#697 feat(msg): add retain flag
  src/assets/scss/mixins.scss
  src/components/MsgLeftItem.vue
Labels: enhancement, UI \ UX

#698 fix(store): fix cant sync the data to shared data
  src/store/modules/app.ts
Labels: fix

#699 style(element): adaptation of the skeleton screen theme
  src/assets/scss/element/element-reset.scss
  src/assets/scss/theme/dark.scss
  src/assets/scss/theme/light.scss
  src/assets/scss/theme/night.scss
Labels: UI \ UX

#700 fix(message): fix message enter & leave flash issue
  src/components/MsgLeftItem.vue
  src/components/MsgRightItem.vue
  src/database/services/ConnectionService.ts
  src/views/connections/ConnectionsDetail.vue
Labels: bug, performance, UI \ UX

#708 fix(subscribe): fix retain message flash/mis-render issue
  src/components/SubscriptionsList.vue
  src/database/services/ConnectionService.ts
Labels: bug

#710 fix(connection): remove useless codes
  src/database/models/HistoryConnectionEntity.ts
  src/database/services/ConnectionService.ts
Labels: enhancement

#712 fix(will): will model cascade remove issue
  src/database/services/ConnectionService.ts
Labels: fix

#711 fix(msgPublish): payload changed after send msg
  src/components/MsgPublish.vue
Labels: fix

#717 fix(history): fix history message record issue
  src/database/services/HistoryMessageHeaderService.ts
  src/database/services/HistoryMessagePayloaderService.ts
  src/utils/mqttUtils.ts
  src/views/connections/ConnectionsDetail.vue
Labels: fix

#718 fix(collection): add delete confirm
  src/views/connections/ConnectionsList.vue
Labels: feature, fix
