Repository emqx/MQTTX, pull requests merged in 2021-02, with the labels that each got.

#489 docs(github): add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#494 docs(github): add cn contributing file
  .github/CONTRIBUTING_CN.md
  README-CN.md
Labels: docs

#496 fix(logs): fix windows filename error & build error
  docs/manual-cn.md
  docs/manual-jp.md
  docs/manual.md
  package.json
  src/main.ts
  src/utils/logger.ts
Labels: fix

#497 fix(cli): fix launch electron failed becauseof vue-cli-plugins updates
  package.json
  src/background.ts
  yarn.lock
Labels: dependencies, fix

#498 fix(MsgPulish): fix editorRef invalidation becauseof route params undefined
  src/components/MsgPublish.vue
Labels: fix

#499 build(win): modify windows package name
  vue.config.js
Labels: upgrade

#500 chore(CI): add github actions
  .github/workflows/build_packages.yaml
  .github/workflows/upload_github_release_asset.sh
Labels: Chore

#503 fix(logs): fix windows filename error & build error
  README-CN.md
  README.md
  package.json
Labels: docs

#504 fix(logs): fix windows filename error & build error
  package.json
  src/main/updateChecker.ts
  src/views/about/index.vue
Labels: upgrade

#512 docs(github): add code of conduct
  .github/CODE_OF_CONDUCT.md
  .github/CODE_OF_CONDUCT_CN.md
Labels: docs

#513 fix(connections): fix can not add error connect fail log
  src/views/connections/ConnectionsDetail.vue
Labels: fix

#514 feat(log): scroll to buttom shen opening log page
  src/components/Editor.vue
  src/views/log/index.vue
Labels: enhancement

#516 fix(logs): fix can't record log message when we send in other filter
  src/views/connections/ConnectionsDetail.vue
Labels: fix

#515 docs(readme): add action status badge
  README-CN.md
  README-JP.md
  README.md
Labels: docs

#517 feat(connection): support quick connection when the panel is folded
  src/views/connections/ConnectionsDetail.vue
Labels: feature

#518 fix(MsgPublish): fix editor error when router jump from other page to creation & connection
  src/components/MsgPublish.vue
  src/views/connections/ConnectionsDetail.vue
Labels: fix

#519 UI(topicList): enhance topic filter click UI\UX
  src/assets/scss/theme/dark.scss
  src/assets/scss/theme/light.scss
  src/assets/scss/theme/night.scss
  src/components/SubscriptionsList.vue
Labels: UI \ UX

#520 style(theme): modify some colors
  src/assets/scss/base.scss
  src/assets/scss/theme/dark.scss
  src/assets/scss/theme/light.scss
  src/components/SubscriptionsList.vue
Labels: UI \ UX

#522 docs(readme): modify mqttx preview image
  assets/mqttx-preview.png
Labels: docs
