Repository emqx/MQTTX, pull requests merged in 2021-01, with the labels that each got.

#442 fix(logs): refactor custom language in Editor components
  src/assets/scss/theme/custom/log-editor-dark.json
  src/assets/scss/theme/custom/log-editor-rules.json
  src/assets/scss/theme/custom/log-editor.json
  src/assets/scss/theme/log-editor-dark.json
  src/components/Editor.vue
  src/views/about/index.vue
  src/views/log/index.vue
Labels: fix

#441 fix(logs): set logger for connectionDetail page
  src/background.ts
  src/components/SubscriptionsList.vue
  src/utils/logger.ts
  src/views/connections/ConnectionsDetail.vue
  src/views/log/index.vue
  vue.config.js
Labels: enhancement, feature

#446 fix(MsgPublish): fix cannot initialized editor jump from creation page
  src/background.ts
  src/components/MsgPublish.vue
  src/views/connections/index.vue
Labels: fix

#449 fix(plugins): fix plugins registered abnormal
  src/components/SubscriptionsList.vue
  src/plugins/logPlugin/index.ts
  src/types/logPlugins.d.ts
  src/utils/element.ts
  src/views/connections/ConnectionsDetail.vue
  src/views/log/index.vue
Labels: fix

#453 fix(ssl): set rejectUnauthorized to true by default
  src/lang/connections.ts
  src/utils/mqttUtils.ts
  src/views/connections/ConnectionForm.vue
Labels: fix

#456 fix(form): fix form item postion issue
  src/assets/scss/base.scss
  src/views/connections/ConnectionForm.vue
Labels: fix

#461 fix(UI): fixed the jitter of the input component
  src/views/connections/ConnectionForm.vue
Labels: UI \ UX, fix

#459 fix(log): add APP init info & enhance connection log
  src/App.vue
  src/views/connections/ConnectionsDetail.vue
Labels: enhancement

#460 fix(ConnectionForm): fix page init issue when create after editing
  src/views/connections/ConnectionForm.vue
Labels: fix

#463 fix(feat): add connect loading icon when the ClientInfo scroll
  src/views/connections/ConnectionsDetail.vue
Labels: UI \ UX, feature

#464 docs(readme): update readme
  README-CN.md
  docs/manual-cn.md
Labels: docs

#465 style(input): reset input number width
  src/assets/scss/element/element-reset.scss
  src/views/connections/ConnectionInfo.vue
Labels: UI \ UX

#467 docs(readme): update emqx logo
  assets/mqttx-preview.png
  assets/wx_qr_code.png
  src/assets/images/emqx-logo.png
  src/assets/images/qq-qr_code.png
  src/assets/images/wx_qr_code.png
  src/views/about/index.vue
Labels: docs

#466 fix(logs): enhance connection protocol info
  src/views/connections/ConnectionsDetail.vue
Labels: fix

#468 chore(package): v1.4.2 -> v1.5.0
  package.json
  src/main/updateChecker.ts
  src/views/about/index.vue
Labels: upgrade

#477 fix(connections): fix the problem that the client id cannot be refreshed
  src/components/Editor.vue
  src/components/MsgPublish.vue
  src/lang/connections.ts
  src/views/connections/ConnectionForm.vue
Labels: fix

#479 docs(issue): add issue template for help wanted and feature request
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/help_wanted.md
Labels: docs, enhancement

#480 docs(logs): add docunmentation for log function
  docs/manual-cn.md
  docs/manual-jp.md
  docs/manual.md
Labels: docs

#481 style(element): modify border radius style
  src/assets/scss/element/element-reset.scss
  src/components/SubscriptionsList.vue
Labels: UI \ UX

#482 fix(MsgPublish): fix multiple editors that were not destroyed
  src/components/Editor.vue
  src/components/MsgPublish.vue
Labels: bug, fix

#484 docs(manual): update manual & issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/help_wanted.md
  docs/manual-cn.md
  docs/manual-jp.md
  docs/manual.md
Labels: docs

#483 fix(log): fix the exception caused by deleting log files when mqttx is running
  src/utils/logger.ts
  src/views/log/index.vue
Labels: fix

#486 chore(package): v1.5.0 -> v1.5.1
  package.json
  src/main/updateChecker.ts
  src/views/about/index.vue
Labels: upgrade
