Repository emqx/MQTTX, pull requests merged in 2021-03, with the labels that each got.

#528 fix(subscription): fix SYS topic reject prompt error
  src/components/SubscriptionsList.vue
  src/lang/connections.ts
Labels: bug

#529 docs(github): fix typo
  .github/CONTRIBUTING_CN.md
Labels: docs

#536 fix(subs): fix copy topic and tooltip disappears
  src/assets/scss/theme/dark.scss
  src/assets/scss/theme/light.scss
  src/assets/scss/theme/night.scss
  src/components/SubscriptionsList.vue
  src/main.ts
Labels: enhancement, fix

#539 feat(connection): support connection collection delete & rename & add(drop)
  src/api/connection.ts
  src/database/index.ts
  src/lang/connections.ts
  src/store/modules/app.ts
  src/types/global.d.ts
  src/utils/getCollectionId.ts
  src/views/connections/ConnectionForm.vue
  src/views/connections/ConnectionsList.vue
  src/views/connections/index.vue
  src/views/connections/types.ts
  src/views/window/Window.vue
Labels: feature
