Repository emqx/MQTTX, pull requests merged in 2021-07, with the labels that each got.

#614 refactor(about): modify logo images
  assets/mqttx-logo.png
  src/assets/images/emq-logo-dark.png
  src/assets/images/emq-logo-light.png
  src/assets/images/emq-logo.png
  src/assets/images/mqttx-dark.png
  src/assets/images/mqttx-light.png
  src/views/about/index.vue
Labels: enhancement, refactor

#615 docs(readme): update readme
  README-CN.md
  README-JP.md
  README.md
Labels: docs

#623 feat(config): adapt to the new mac icon
  public/icons/Icon.icns
  public/icons/app.ico
  public/icons/app.png
  public/icons/mac/Icon.icns
  public/index.html
  vue.config.js
Labels: UI \ UX, enhancement

#626 add Turkish language support
  src/lang/about.ts
  src/lang/common.ts
  src/lang/connections.ts
  src/lang/index.ts
  src/lang/log.ts
  src/lang/script.ts
  src/lang/settings.ts
  src/types/global.d.ts
  src/types/locale.d.ts
  src/views/settings/index.vue
Labels: enhancement

#628 feat(config): add support for mac universal arch
  package.json
  vue.config.js
  yarn.lock
Labels: enhancement

#629 fix(i18n): add missing theme options i18n
  src/lang/settings.ts
  src/views/settings/index.vue
Labels: enhancement

#630 chore(package): fixed the sass version
  package.json
  yarn.lock
Labels: dependencies, fix

#639 refactor(types): migrate types
  .eslintrc.js
  src/api/connection.ts
  src/api/script.ts
  src/components/ExportData.vue
  src/components/ImportData.vue
  src/components/Leftbar.vue
  src/components/MessageList.vue
  src/components/MsgPublish.vue
  src/components/MsgTypeTabs.vue
  src/components/SubscriptionsList.vue
  src/components/UseScript.vue
  src/database/index.ts
  src/router/index.ts
  src/router/routes.ts
  src/store/modules/app.ts
  src/types/global.d.ts
  src/utils/SystemTopicUtils.ts
  src/utils/connections.ts
  src/utils/getFiles.ts
  src/utils/mqttUtils.ts
  src/utils/topicMatch.ts
  src/views/about/index.vue
  src/views/connections/ConnectionForm.vue
  src/views/connections/ConnectionInfo.vue
  src/views/connections/ConnectionsDetail.vue
  src/views/connections/ConnectionsList.vue
  src/views/connections/index.vue
  src/views/connections/types.ts
  src/views/script/index.vue
  src/views/script/types.ts
  src/views/window/Window.vue
Labels: refactor

#640 refactor(types): imporve types defined
  src/types/global.d.ts
  src/views/connections/ConnectionForm.vue
  src/views/connections/ConnectionInfo.vue
  src/views/connections/ConnectionsDetail.vue
Labels: refactor

#642 refactor(connection): remove client property on connection model
  src/components/SubscriptionsList.vue
  src/types/global.d.ts
  src/utils/mqttUtils.ts
  src/views/connections/ConnectionForm.vue
  src/views/connections/ConnectionsDetail.vue
  src/views/connections/index.vue
  src/views/window/Window.vue
Labels: enhancement, refactor

#644 style(element): change button border width to 1px
  src/assets/scss/element/element-reset.scss
  src/views/script/index.vue
Labels: UI \ UX

#645 feat(db): add service layer
  package.json
  src/api/connection.ts
  src/background.ts
  src/components/MessageList.vue
  src/components/MsgPublish.vue
  src/components/SubscriptionsList.vue
  src/database/database.config.ts
  src/database/models/ConnectionEntity.ts
  src/database/models/MessageEntity.ts
  src/database/models/WillEntity.ts
  src/database/services/ConnectionService.ts
  src/database/useConnection.ts
  src/database/useServices.ts
  src/database/useSqlite.ts
  src/main.ts
  src/types/global.d.ts
  src/utils/mqttUtils.ts
  src/views/connections/ConnectionForm.vue
  src/views/connections/ConnectionInfo.vue
  src/views/connections/ConnectionsDetail.vue
  src/views/connections/ConnectionsList.vue
  yarn.lock
Labels: feature, refactor

#647 refactor(settings): refactor settings model
  package.json
  src/background.ts
  src/database/database.config.ts
  src/database/migration/1627697951611-initTable.ts
  src/database/models/SettingEntity.ts
  src/database/services/SettingService.ts
  src/database/useServices.ts
Labels: refactor
