Repository emqx/MQTTX, pull requests merged in 2021-12, with the labels that each got.

#797 style(msg): modify user properties display styles
  src/assets/scss/mixins.scss
  src/assets/scss/theme/dark.scss
  src/assets/scss/theme/light.scss
  src/assets/scss/theme/night.scss
  src/components/MsgLeftItem.vue
  src/components/MsgPublish.vue
  src/components/MsgRightItem.vue
Labels: enhancement, UI \ UX

#795 WIP: feat(connection): support rest connection props
  src/lang/connections.ts
  src/types/global.d.ts
  src/utils/mqttUtils.ts
  src/views/connections/ConnectionForm.vue
Labels: feature

#800 feat(settings): sync with os theme setting
  src/background.ts
  src/components/Editor.vue
  src/main/systemTheme.ts
  src/views/Home.vue
Labels: enhancement, feature

#803 fix(message): fix message prop incorrect insert
  src/components/MsgPublish.vue
  src/database/models/ConnectionEntity.ts
  src/database/services/MessageService.ts
  src/views/connections/ConnectionsDetail.vue
Labels: fix

#804 fix(msg): fix save properties issue
  src/components/MsgPublish.vue
  src/views/connections/ConnectionsDetail.vue
Labels: fix

#805 chore(package): bump mqtt to 4.2.8
  package.json
  src/components/MsgPublish.vue
  src/utils/mqttUtils.ts
  yarn.lock
Labels: dependencies

#807 fix(message): fix message prop incorrect insert
  src/database/services/ConnectionService.ts
Labels: fix

#808 fix(msg): add confirm reset prompt and fix can not load user properties
  src/components/MsgPublish.vue
  src/lang/common.ts
  src/types/global.d.ts
Labels: enhancement, feature, fix

#809 fix(msg): fix correlation data is buffer type
  src/database/services/MessageService.ts
  src/types/global.d.ts
  src/views/connections/ConnectionsDetail.vue
Labels: enhancement, fix

#811 feat(components): add key value editor component
  src/components/KeyValueEditor.vue
  src/components/MsgPublish.vue
  src/views/connections/ConnectionForm.vue
Labels: enhancement, feature, refactor

#813 feat(connection): add unit for connection form
  src/views/connections/ConnectionForm.vue
Labels: enhancement

#817 fix(connection): fix pass the __ob__ field to user properties
  src/views/connections/ConnectionsDetail.vue
Labels: fix

#818 fix(connection): fix client id is unique in database
  src/database/database.config.ts
  src/database/migration/1639031638009-clientid.ts
  src/database/models/ConnectionEntity.ts
Labels: fix

#820 fix(connection): add unit to session expiry interval
  src/views/connections/ConnectionForm.vue
Labels: enhancement

#822 feat(subscriptions): add sub identifier field
  src/components/SubscriptionsList.vue
  src/database/database.config.ts
  src/database/migration/1639375963172-subscriptionIdentifier.ts
  src/database/models/SubscriptionEntity.ts
Labels: feature, migration

#825 fix(msg): remove reset meta data function
  src/components/MsgPublish.vue
Labels: enhancement, fix, refactor

#826 fix(connection): fix can sent empty topic when set the topic alias
  src/views/connections/ConnectionsDetail.vue
Labels: enhancement, fix

#831 feat(log): add properties log
  src/components/SubscriptionsList.vue
  src/views/connections/ConnectionsDetail.vue
Labels: enhancement, feature

#832 fix(subs): fix resub can not sync the all data
  src/components/SubscriptionsList.vue
Labels: fix

#834 docs(readme): update readme
  README.md
Labels: docs

#835 feat(about): add try mqtt cloud button
  src/assets/font/iconfont.css
  src/assets/font/iconfont.js
  src/assets/font/iconfont.json
  src/assets/font/iconfont.ttf
  src/assets/font/iconfont.woff
  src/assets/font/iconfont.woff2
  src/components/EmptyPage.vue
  src/lang/about.ts
  src/lang/common.ts
  src/views/about/index.vue
Labels: enhancement, refactor, UI \ UX

#837 style(index): update loading page when first load page
  public/favicon.ico
  public/index.html
Labels: UI \ UX

#840 feat(connection): display response topic correlation data and topic a…
  src/assets/scss/mixins.scss
  src/components/MsgLeftItem.vue
  src/components/MsgRightItem.vue
Labels: enhancement, feature

#841 feat(about): update about page
  src/lang/about.ts
  src/lang/common.ts
  src/views/about/index.vue
Labels: enhancement, refactor

#842 docs(manual): update docs images
  assets/mqttx-advance.png
  assets/mqttx-brokerinfo.png
  assets/mqttx-bytes.png
  assets/mqttx-certs.png
  assets/mqttx-connection.png
  assets/mqttx-create.png
  assets/mqttx-log.png
  assets/mqttx-main.png
  assets/mqttx-message.png
  assets/mqttx-muti-window.png
  assets/mqttx-script.png
  assets/mqttx-search.png
  assets/mqttx-theme.png
  assets/mqttx-timed-message.png
  assets/mqttx-topic-alias.png
  assets/mqttx-topic.png
  assets/mqttx-update.png
  assets/mqttx-user.png
  assets/mqttx-v5.png
  assets/mqttx-willmessage.png
  assets/mqttx-window.png
  docs/manual-cn.md
  docs/manual-jp.md
  docs/manual.md
Labels: docs

#843 fix(import): collection importing issue
  src/database/services/ConnectionService.ts
Labels: fix

#844 docs(readme): update readme
  README.md
Labels: docs

#846 docs(manual): update docs
  assets/mqttx-autoscroll.png
  assets/mqttx-muti-topics.png
  docs/manual-cn.md
  docs/manual.md
Labels: docs

#848 chore(package): bump mqtt to 4.3.0 to fix types error
  package.json
  src/components/SubscriptionsList.vue
  src/router/index.ts
  src/views/connections/ConnectionsDetail.vue
  yarn.lock
Labels: fix, dependencies, Chore

#851 fix(connection): fix sync auto resub issue
  src/types/global.d.ts
  src/utils/mqttUtils.ts
  src/views/about/index.vue
  src/views/connections/ConnectionForm.vue
  src/views/connections/ConnectionsDetail.vue
Labels: fix

#852 fix(connection): isolating connections in the new window
  src/views/connections/ConnectionsList.vue
Labels: enhancement, fix

#853 refactor(log): improve the log info
  src/views/connections/ConnectionsDetail.vue
Labels: enhancement, refactor

#854 fix(connection): fix can not display offline message when connected
  src/views/connections/ConnectionsDetail.vue
Labels: fix

#857 feat(log): add some logs
  src/views/connections/ConnectionsDetail.vue
Labels: enhancement
