Repository emqx/MQTTX, pull requests merged in 2021-11, with the labels that each got.

#767 fix(MsgPublish): fix base64 convert issue
  src/utils/convertPayload.ts
Labels: fix

#773 fix(newWindows): fix new windows loading issue
  src/main/newWindow.ts
Labels: fix

#774 fix(connectionHistory): history connection duplication id issue
  src/database/models/HistoryConnectionEntity.ts
  src/database/services/ConnectionService.ts
Labels: fix

#775 fix(connectionList): unexpected collectionId update issue
  src/database/services/ConnectionService.ts
Labels: bug

#779 1.7.0
  package.json
  src/main/updateChecker.ts
  src/version.ts
Labels: upgrade

#783 docs: add faq
  docs/manual-cn.md
  docs/manual-jp.md
  docs/manual.md
Labels: docs

#785 refactor(mqtt5): adjust meta card UI
  src/components/MsgPublish.vue
Labels: UI \ UX

#786 style(meta): modify some meta card styles
  src/components/MsgPublish.vue
Labels: UI \ UX

#788 feat(subscriptions): support subscribe muti-topics
  src/components/SubscriptionsList.vue
  src/database/services/ConnectionService.ts
  src/lang/connections.ts
Labels: feature

#790 fix(subscribe): multi subscribes insert issue
  src/components/SubscriptionsList.vue
  src/database/services/ConnectionService.ts
Labels: fix

#794 fix(msg): fix display user props issue
  src/components/MsgLeftItem.vue
  src/components/MsgRightItem.vue
  src/views/connections/ConnectionsDetail.vue
Labels: fix

#796 feat(msg): add tooltip when meta button disabled
  src/components/MsgPublish.vue
  src/lang/connections.ts
Labels: enhancement, feature
