Repository emqx/MQTTX, pull requests merged in 2022-12, with the labels that each got.

#1170 improve(desktop): remove vuex all connections data
  src/components/ExportData.vue
  src/database/services/ConnectionService.ts
  src/store/modules/app.ts
  src/views/connections/ConnectionForm.vue
  src/views/connections/ConnectionInfo.vue
  src/views/connections/index.vue
Labels: performance, Desktop

#1172 refactor(topic): add topic input box prompt
  src/components/MsgPublish.vue
  src/lang/connections.ts
  src/views/connections/ConnectionsDetail.vue
Labels: enhancement, Desktop

#1174 improve(desktop): improve update subscriptions logic
  src/components/SubscriptionsList.vue
  src/database/services/ConnectionService.ts
  src/database/services/SubscriptionService.ts
  src/database/useServices.ts
Labels: performance, Desktop

#1177 chore(pkg): upgrade version 1.9.1-beta.1
  cli/package.json
  package.json
  src/version.ts
  web/package.json
Labels: upgrade

#1180 refactor(ui): ui/ue enhancement
  src/assets/scss/element/element-reset.scss
  src/views/connections/ConnectionsDetail.vue
  src/views/settings/index.vue
Labels: enhancement, UI \ UX
