Repository emqx/MQTTX, pull requests merged in 2022-01, with the labels that each got.

#862 docs(readme): update readme
  README-CN.md
  README.md
Labels: docs

#865 docs(readme): update readme
  README.md
Labels: docs

#866 feat(connection): add reconnect period field
  src/database/database.config.ts
  src/database/migration/1642321826532-reconnectPeriod.ts
  src/database/models/ConnectionEntity.ts
  src/database/models/HistoryConnectionEntity.ts
  src/types/global.d.ts
  src/utils/mqttUtils.ts
Labels: feature, migration

#867 chore(pkg): 1.7.1 -> 1.7.2
  package.json
  src/version.ts
Labels: upgrade

#868 feat(connection): support set reconnect period when create
  src/lang/connections.ts
  src/views/connections/ConnectionForm.vue
Labels: feature

#873 refactor(cloud): change basic trial days
  src/lang/common.ts
Labels: refactor, docs

#876 fix(subscription): fix sublist refrence copy issue
  src/components/SubscriptionsList.vue
Labels: fix

#877 feat(topicMatch): support shared subscription marker topic colors
  src/utils/topicMatch.ts
Labels: enhancement, feature, fix

#879 style(msg): modify msg item max width
  src/assets/scss/mixins.scss
Labels: enhancement, fix, UI \ UX

#880 refactor(about): add discord
  src/assets/font/iconfont.css
  src/assets/font/iconfont.js
  src/assets/font/iconfont.json
  src/assets/font/iconfont.ttf
  src/assets/font/iconfont.woff
  src/assets/font/iconfont.woff2
  src/views/about/index.vue
Labels: refactor

#882 docs(readme): update readme
  README-CN.md
  README-JP.md
  README.md
Labels: docs
