Repository emqx/MQTTX, pull requests merged in 2022-08, with the labels that each got.

#1022 fix(connection): fix $ symbol invalid
  src/lang/connections.ts
  src/views/connections/ConnectionsDetail.vue
Labels: fix, Desktop

#1025 docs(readme): update readme
  README.md
  docs/manual.md
Labels: docs

#1026 chore(pkg): 1.8.1 -> 1.8.2
  cli/package.json
  package.json
  src/version.ts
  web/package.json
Labels: upgrade

#1027 fix(lang): fix sub qos failed tips
  src/lang/connections.ts
Labels: fix, Desktop

#1028 fix(updater): replace download to install
  src/main/updateChecker.ts
Labels: enhancement, Desktop

#1031 feat(settings): add multi topics field
  src/database/database.config.ts
  src/database/migration/1659668384878-multiTopics.ts
  src/database/models/SettingEntity.ts
  src/store/getter.ts
  src/store/modules/app.ts
  src/types/global.d.ts
Labels: feature, migration, Desktop

#1032 feat(subscriptions): support disable and enable multi-topics
  src/background.ts
  src/components/SubscriptionsList.vue
  src/lang/settings.ts
  src/store/modules/app.ts
  src/views/settings/index.vue
Labels: enhancement, feature

#1034 docs(readme): update readme
  cli/README-CN.md
  cli/README.md
Labels: docs, upgrade, CLI

#1038 chore(links): add parameters to URLs to identify the campaigns that refer traffic
  src/components/EmptyPage.vue
  src/components/Leftbar.vue
  src/lang/common.ts
  src/utils/gaCustomLinks.ts
  src/views/about/index.vue
Labels: Desktop

#1037 fix(Topic Aliases): not able to receive messages with Topic Alias set
  src/utils/mqttUtils.ts
Labels: fix, Desktop

#1043 fix(desktop): fix history message header update bug
  src/database/services/HistoryMessageHeaderService.ts
Labels: fix, Desktop

#1044 feat(web): add payload & topic history of sent messages
  web/src/components/MsgPublish.vue
  web/src/database/index.ts
  web/src/utils/api/historyMessageHeaderService.ts
  web/src/utils/api/historyMessagePayloadService.ts
  web/src/utils/historyRecordUtils.ts
  web/src/views/connections/ConnectionsDetail.vue
Labels: feature, Web

#1045 docs(readme): update readme
  README-CN.md
  README.md
Labels: docs

#1053 feat(web): set the publicPath to '/' when building the docker image
  .github/workflows/deploy_web.yaml
  web/package.json
  web/vue.config.js
Labels: Web

#1054 feat(web): add connect btn to topbar
  web/src/store/modules/app.ts
  web/src/views/connections/ConnectionsDetail.vue
Labels: Web

#1056 fix(desktop): fix subscription color bug
  src/components/SubscriptionsList.vue
Labels: bug, Desktop

#1058 feat(web): support multi topics subscribe
  web/src/components/SubscriptionsList.vue
  web/src/database/index.ts
  web/src/lang/settings.ts
  web/src/store/getter.ts
  web/src/store/modules/app.ts
  web/src/types/global.d.ts
  web/src/views/settings/index.vue
Labels: feature, Web

#1059 feat(web): support autoscroll setting
  web/src/database/index.ts
  web/src/lang/settings.ts
  web/src/store/getter.ts
  web/src/store/modules/app.ts
  web/src/types/global.d.ts
  web/src/views/connections/ConnectionsDetail.vue
  web/src/views/settings/index.vue
Labels: feature, Web
