Repository emqx/MQTTX, pull requests merged in 2022-04, with the labels that each got.

#926 docs(readme): update readme
  README-CN.md
  README-JP.md
  README.md
  docs/manual-cn.md
  docs/manual-jp.md
  docs/manual.md
Labels: docs

#932 chore(deps): bump sqlite3 to 5.0.4 compatible with apple M1
  package.json
  yarn.lock
Labels: dependencies, Chore

#934 docs(readme): update readme
  README-CN.md
  README.md
Labels: docs

#936 fix(sidebar): fix sidebar activation status error
  src/components/Leftbar.vue
Labels: fix
