Repository emqx/MQTTX, pull requests merged in 2022-06, with the labels that each got.

#943 feat(menu): add new window menu
  src/components/Ipc.vue
  src/main/getMenuTemplate.ts
  src/views/connections/ConnectionsDetail.vue
Labels: enhancement

#944 feat(connection): support duplicate the connection
  src/lang/common.ts
  src/lang/connections.ts
  src/views/connections/ConnectionsList.vue
Labels: enhancement, feature

#949 chore(cloud-link): modify utm source for cloud link
  src/lang/common.ts
Labels: enhancement

#952 fix(lang): fix some case issue
  src/components/ClearUpHistoryData.vue
  src/lang/common.ts
  src/lang/connections.ts
  src/lang/script.ts
Labels: enhancement, fix

#953 fix(message): fix can not clear long message
  src/components/MessageList.vue
  src/views/connections/ConnectionsDetail.vue
Labels: fix

#955 fix(message): fix show duplicate long message in diff connection
  src/views/connections/ConnectionsDetail.vue
Labels: fix

#957 chore(package): bump electron builder deps & remove build universal packages
  package.json
  vue.config.js
  yarn.lock
Labels: dependencies, Chore

#961 docs(readme): update cli readme
  assets/mqttx-cli-preview.png
  cli/LICENSE
  cli/README-CN.md
  cli/README.md
Labels: docs

#962 docs(readme): update web readme
  assets/mqttx-web-preview.png
  cli/README-CN.md
  cli/README.md
  web/README.md
Labels: docs

#963 docs(readme): update cli readme
  cli/README.md
Labels: docs

#964 docs(readme): update cli readme
  cli/README-CN.md
  cli/README.md
Labels: docs

#966 chore(cli): release mqttx-cli v1.8.1
  cli/package.json
Labels: upgrade

#967 docs(readme): update web readme
  cli/README-CN.md
  cli/README.md
  web/README-CN.md
  web/README.md
Labels: docs

#971 feat(cli): add main module & modify bin executable file
  cli/.gitignore
  cli/.npmignore
  cli/bin/index.js
  cli/package.json
  cli/src/index.ts
  cli/src/lib/pub.ts
  cli/src/lib/sub.ts
  cli/tsconfig.json
Labels: refactor, CLI

#972 docs(readme): update homebrew
  cli/README-CN.md
  cli/README.md
  web/README-CN.md
Labels: docs, CLI
