Repository emqx/MQTTX, pull requests merged in 2023-04, with the labels that each got.

#1259 fix(message): fix break word styles
  src/assets/scss/base.scss
Labels: enhancement, Desktop

#1263 fix(mqtt): handle missing username with password
  src/utils/mqttUtils.ts
  src/views/connections/ConnectionsDetail.vue
Labels: enhancement, fix, Desktop

#1266 fix(connections): improve connection handling when set selected conne…
  src/store/modules/app.ts
  src/views/connections/index.vue
Labels: enhancement, fix, Desktop

#1267 fix(keyvalue): trigger change event with null
  src/components/KeyValueEditor.vue
Labels: fix, Desktop

#1268 fix(meta): fix meta data saving issue requiring two clicks
  src/components/MsgPublish.vue
Labels: fix, Desktop

#1271 fix(type): remove useless type define
  src/types/global.d.ts
Labels: enhancement, fix

#1272 feat(gtm): add google tag manager
  web/package.json
  web/src/main.ts
  web/src/router/index.ts
  web/yarn.lock
Labels: Chore, Web

#1274 fix(cli): fix typo
  cli/README-CN.md
  cli/README.md
  cli/src/index.ts
  cli/src/lib/conn.ts
  cli/src/lib/pub.ts
  cli/src/lib/sub.ts
  cli/src/types/global.d.ts
Labels: fix, CLI

#1275 docs(readme): update readme
  cli/README-CN.md
  cli/README.md
Labels: docs, CLI
