Repository emqx/MQTTX, pull requests merged in 2023-02, with the labels that each got.

#1220 fix(desktop): fix the bug of import xml or csv file
  package.json
  src/components/ExportData.vue
  src/components/ImportData.vue
  src/types/shims-vue.d.ts
  src/utils/exportData.ts
  yarn.lock
Labels: fix, Desktop

#1221 improve(desktop): add loading animation for import data
  src/assets/scss/theme/dark.scss
  src/components/ImportData.vue
  src/utils/element.ts
  src/views/connections/ConnectionsDetail.vue
Labels: UI \ UX, Desktop

#1222 feat(desktop): add import data tip
  src/components/ImportData.vue
  src/lang/connections.ts
  src/utils/element.ts
Labels: UI \ UX, Desktop

#1223 style(desktop): modify some styles of the import data tip
  src/components/ImportData.vue
Labels: UI \ UX, Desktop

#1226 docs(cli): update readme
  cli/README-CN.md
  cli/README.md
Labels: docs, CLI

#1227 feat(cli): support output mode for the sub command
  cli/src/index.ts
  cli/src/lib/sub.ts
  cli/src/types/global.d.ts
  cli/src/utils/parse.ts
Labels: feature, CLI

#1229 improve(desktop): add loading animation for export data
  src/components/ExportData.vue
Labels: UI \ UX, Desktop

#1230 improve(desktop): prioritize loading of the most recently selected co…
  src/router/index.ts
  src/store/modules/app.ts
  src/types/global.d.ts
  src/views/connections/index.vue
Labels: fix, Desktop

#1234 chore(pkg): fixed vm version
  package.json
  yarn.lock
Labels: dependencies, Desktop

#1235 improve(desktop): add title attribute to history topic
  src/components/MsgPublish.vue
  web/src/components/MsgPublish.vue
Labels: UI \ UX, Web, Desktop

#1239 refactor(mqtt): improve code readability
  cli/src/utils/parse.ts
  src/utils/mqttUtils.ts
Labels: enhancement, Desktop
