Repository emqx/MQTTX, pull requests merged in 2023-08, with the labels that each got.

#1381 feat(msg-left-item):support json highlight
  babel.config.js
  package.json
  src/components/MsgLeftItem.vue
  yarn.lock
Labels: enhancement, feature

#1383 improve(msg-left-item):add msg type meta props
  src/components/MsgLeftItem.vue
  src/utils/validFormatJson.ts
  src/views/connections/ConnectionsDetail.vue
Labels: fix, desktop

#1384 style(msg-left-item):modify topic color bar
  src/components/MsgLeftItem.vue
Labels: fix

#1385 feat(msg): change the highlight code theme
  babel.config.js
  src/assets/scss/base.scss
  src/assets/scss/theme/custom/prism-one-dark.scss
  src/assets/scss/theme/custom/prism-one-light.scss
  src/components/MsgLeftItem.vue
Labels: enhancement, feature, UI \ UX, desktop

#1387 fix(script): adapt the tabs border color to dark mode
  src/components/MsgLeftItem.vue
  src/views/script/index.vue
Labels: fix, UI \ UX, desktop

#1389 chore(pkg): upgrade version 1.9.5
  cli/package.json
  package.json
  src/version.ts
  web/package.json
Labels: upgrade

#1392 chore(ci): fix can not cp to aws s3
  .github/workflows/build_packages.yaml
Labels: chore

#1399 feat(connection): ALPN protocols support
  src/database/database.config.ts
  src/database/migration/1691817588169-ALPNProtocols.ts
  src/database/models/ConnectionEntity.ts
  src/database/models/HistoryConnectionEntity.ts
  src/types/global.d.ts
  src/utils/mqttUtils.ts
  src/views/connections/ConnectionForm.vue
Labels: feature, desktop

#1397 Draft documents for MQTTX Desktop - Get Started
  docs/desktop/en/advanced/advanced-setting.md
  docs/desktop/en/downloading-and-installation.md
  docs/desktop/en/introduction.md
  docs/desktop/en/quick-start/assets/mqttx-brokerinfo.png
  docs/desktop/en/quick-start/assets/mqttx-connected.png
  docs/desktop/en/quick-start/assets/new-connection.png
  docs/desktop/en/quick-start/assets/new-subscribe.png
  docs/desktop/en/quick-start/assets/publish.png
  docs/desktop/en/quick-start/assets/receive.png
  docs/desktop/en/quick-start/get-started.md
  docs/desktop/en/use-desktop/assets/connection-advanced.png
  docs/desktop/en/use-desktop/assets/mqttx-brokerinfo.png
  docs/desktop/en/use-desktop/assets/mqttx-certs.png
  docs/desktop/en/use-desktop/assets/mqttx-user.png
  docs/desktop/en/use-desktop/connect.md
  docs/desktop/en/use-desktop/pub-sub.md
  docs/desktop/zh/advanced/advanced-setting.md
  docs/desktop/zh/downloading-and-installation.md
  docs/desktop/zh/introduction.md
  docs/desktop/zh/quick-start/assets/mqttx-brokerinfo.png
  docs/desktop/zh/quick-start/assets/mqttx-connected.png
  docs/desktop/zh/quick-start/assets/new-connection.png
  docs/desktop/zh/quick-start/assets/new-subscribe.png
  docs/desktop/zh/quick-start/assets/publish.png
  docs/desktop/zh/quick-start/assets/receive.png
  docs/desktop/zh/quick-start/get-started.md
  docs/desktop/zh/use-desktop/assets/connection-advanced.png
  docs/desktop/zh/use-desktop/assets/mqttx-brokerinfo.png
  docs/desktop/zh/use-desktop/assets/mqttx-certs.png
  docs/desktop/zh/use-desktop/assets/mqttx-user.png
  docs/desktop/zh/use-desktop/connect.md
  docs/desktop/zh/use-desktop/pub-sub.md
Labels: docs

#1402 docs: update markdonw format
  docs/desktop/en/advanced/advanced-setting.md
  docs/desktop/en/quick-start/get-started.md
  docs/desktop/en/use-desktop/connect.md
  docs/desktop/en/use-desktop/pub-sub.md
  docs/desktop/zh/advanced/advanced-setting.md
  docs/desktop/zh/quick-start/get-started.md
  docs/desktop/zh/use-desktop/connect.md
  docs/desktop/zh/use-desktop/pub-sub.md
Labels: docs
