Repository emqx/MQTTX, pull requests merged in 2023-09, with the labels that each got.

#1409 feat(settings): clear history data include all messages
  src/components/ClearUpHistoryData.vue
  src/database/services/MessageService.ts
  src/lang/settings.ts
Labels: enhancement, desktop

#1413 fix(cli): fix pub the wrong base64 formart message
  cli/src/lib/pub.ts
  cli/src/lib/sub.ts
  cli/src/utils/convertPayload.ts
  cli/src/utils/protobuf.ts
Labels: enhancement, fix, refactor, CLI

#1415 fix(msg): incomplete display mqtt5 properties in message box
  src/components/MsgLeftItem.vue
  src/components/MsgPublish.vue
  src/components/MsgRightItem.vue
Labels: enhancement, fix, desktop

#1419 fix(web):fix type conversion of received json messages
  web/src/views/connections/ConnectionsDetail.vue
Labels: bug, web

#1426 fix(CI): change download to secure https://
  .github/workflows/deploy_web.yaml
Labels: CI/CD

#1424 fix(theme): add unit to avoid deprecation warning
  src/assets/scss/theme/custom/prism-one-light.scss
Labels: enhancement, chore

#1430 fix(docs): branch name changed to `main`
  .github/CONTRIBUTING.md
  .github/CONTRIBUTING_CN.md
Labels: enhancement, fix, docs

#1425 feat(deps): add engines
  cli/package.json
  package.json
  web/package.json
Labels: dependencies, chore

#1436 fix(docs): change links to https
  .github/CODE_OF_CONDUCT.md
  .github/CODE_OF_CONDUCT_CN.md
  README-CN.md
  README-JP.md
  README.md
  cli/README-CN.md
  cli/README.md
  web/README-CN.md
  web/README.md
Labels: fix, docs

#1432 chore(deps): remove unused `axios`
  web/package.json
  web/yarn.lock
Labels: dependencies, chore, web

#1443 fix(publish): remove unuse placeholder
  src/components/MsgPublish.vue
  web/src/components/MsgPublish.vue
Labels: enhancement, UI/UX, web, desktop

#1445 fix(web):fix topic-alias-maximum error in connect
  web/src/utils/mqttUtils.ts
Labels: bug, fix, web
