Repository emqx/MQTTX, pull requests merged in 2023-12, with the labels that each got.

#1510 feat(copilot): support onclick to ask and analyze error msg
  src/assets/scss/base.scss
  src/components/Copilot.vue
  src/components/SubscriptionsList.vue
  src/lang/common.ts
  src/utils/idGenerator.ts
  src/views/connections/ConnectionsDetail.vue
  src/views/settings/index.vue
Labels: feature, desktop

#1514 refactor(database): add copilot table migrate script
  src/database/database.config.ts
  src/database/migration/1701936842016-aiTables.ts
Labels: refactor, migration, desktop

#1515 fix:throw an error for invaild json string
  cli/src/utils/jsonUtils.ts
  src/utils/jsonUtils.ts
  web/src/utils/jsonUtils.ts
Labels: CLI, web, desktop

#1517 feat(copilot): support highlight more code lang
  babel.config.js
  src/main.ts
Labels: enhancement, feature, desktop

#1522 fix(connections): fix can send empty auth info
  src/utils/mqttUtils.ts
Labels: fix, desktop

#1523 feat(copilot): add preset prompt select component
  src/components/Copilot.vue
  src/components/PresetPromptSelect.vue
Labels: enhancement, feature, desktop

#1524 feat(copilot): stream response support
  src/components/Copilot.vue
  src/utils/copilot.ts
Labels: enhancement, feature, desktop

#1525 feat(copilot): add more mqtt faqs preset prompts
  src/components/PresetPromptSelect.vue
  src/lang/common.ts
Labels: feature, desktop

#1527 refactor(connection): replace chart.js to echart
  package.json
  src/components/BytesStatistics.vue
  src/components/charts/AreaLine.vue
  src/components/widgets/BytesStatistics.vue
  src/lang/connections.ts
  src/types/global.d.ts
  src/types/shims-vue.d.ts
  src/views/connections/ConnectionsDetail.vue
  yarn.lock
Labels: enhancement, refactor, dependencies, desktop

#1529 feat(copilot): take connection info when ask error prompt
  src/lang/common.ts
  src/views/connections/ConnectionsDetail.vue
  yarn.lock
Labels: enhancement, desktop

#1533 fix(copilot): update temp value in openai api
  src/components/Copilot.vue
Labels: enhancement, desktop

#1535 feat(copilot): add copy and insert button in code block
  src/assets/scss/theme/custom/prism-one-dark.scss
  src/assets/scss/theme/custom/prism-one-light.scss
  src/background.ts
  src/components/Copilot.vue
  src/components/Ipc.vue
  src/components/MsgLeftItem.vue
  src/components/MsgPublish.vue
  src/components/PresetPromptSelect.vue
  src/lang/common.ts
  src/store/getter.ts
  src/store/modules/app.ts
  src/types/global.d.ts
  src/views/connections/ConnectionsDetail.vue
Labels: enhancement, feature, desktop

#1537 feat(copilot): add more internal prompts
  src/components/Copilot.vue
  src/components/PresetPromptSelect.vue
  src/lang/common.ts
Labels: enhancement, feature, desktop

#1540 fix(cli): omit debug type in bench types
  cli/src/types/global.d.ts
Labels: enhancement, fix, CLI

#1543 docs(cli): update cli readme
  cli/README.md
Labels: docs, CLI
