Repository emqx/MQTTX, pull requests merged in 2023-01, with the labels that each got.

#1188 chore(about): set copyright to automatically update
  src/views/about/index.vue
  web/src/views/about/index.vue
Labels: Web, Desktop

#1189 fix(desktop): fix some bugs of the new window
  src/views/connections/ConnectionsList.vue
  src/views/window/Window.vue
Labels: fix, Desktop

#1190 improve(desktop): improve messages loading logic
  src/database/services/ConnectionService.ts
  src/database/services/MessageService.ts
  src/types/global.d.ts
  src/views/connections/ConnectionsDetail.vue
  src/views/connections/index.vue
Labels: fix, performance, Desktop

#1195 chore(pkg): upgrade version 1.9.1-beta.2
  cli/package.json
  package.json
  src/version.ts
  web/package.json
Labels: upgrade

#1196 improve(desktop): improve code for new message notifications
  src/components/MessageList.vue
  src/components/MsgTip.vue
  src/lang/common.ts
  src/views/connections/ConnectionsDetail.vue
Labels: Desktop

#1197 docs(help): update MQTT beginner's guide
  src/lang/help.ts
  web/src/lang/help.ts
Labels: docs, Web, Desktop

#1198 improve(desktop): improve search message method
  src/database/services/MessageService.ts
  src/views/connections/ConnectionsDetail.vue
Labels: performance, Desktop

#1199 feat(cli): display date
  cli/src/lib/pub.ts
  cli/src/lib/sub.ts
  cli/src/utils/signale.ts
Labels: UI \ UX, CLI

#1200 fix(desktop): fix connect bug
  src/utils/mqttUtils.ts
Labels: fix, Desktop

#1201 feat(desktop): add tooltip to connection group
  src/views/connections/ConnectionsList.vue
Labels: UI \ UX, Desktop

#1202 style(desktop): modify new message notification style
  src/components/MsgTip.vue
Labels: UI \ UX, Desktop

#1203 improve(desktop): improve rendering message method
  src/store/modules/app.ts
  src/types/global.d.ts
  src/views/connections/ConnectionsDetail.vue
Labels: performance, Desktop

#1204 fix(desktop): fix topic input foucs
  src/components/MessageList.vue
  src/views/connections/ConnectionsDetail.vue
Labels: fix, Desktop

#1205 fix(desktop): fix connections list highlight
  src/views/connections/ConnectionsList.vue
Labels: fix, Desktop

#1206 fix(desktop): fix data import
  src/database/services/ConnectionService.ts
Labels: fix, Desktop

#1207 fix(msg): add active status on pub btn
  src/components/MsgPublish.vue
  web/src/components/MsgPublish.vue
Labels: enhancement, Desktop

#1208 fix(desktop): fix bytes statistics
  src/components/SubscriptionsList.vue
Labels: fix, Desktop

#1212 fix(desktop): fix the issue of lost message data in exporting data
  src/components/ExportData.vue
  src/database/services/ConnectionService.ts
Labels: fix, Desktop

#1214 fix(desktop): fix contextmenu position
  src/components/SubscriptionsList.vue
  src/utils/getContextmenuPosition.ts
  src/views/connections/ConnectionsDetail.vue
  src/views/connections/ConnectionsList.vue
Labels: fix, Desktop

#1215 fix(desktop): fix subscribe form reset fields
  src/components/SubscriptionsList.vue
Labels: fix, Desktop

#1216 chore(pkg): upgrade version 1.9.1
  cli/package.json
  package.json
  src/version.ts
  web/package.json
Labels: upgrade

#1217 fix(editor): fix edtior not adapted to window resizing
  src/components/Editor.vue
Labels: fix, Desktop
