Repository emqx/MQTTX, pull requests merged in 2023-07, with the labels that each got.

#1339 feat(connections):add script tags
  src/assets/scss/theme/dark.scss
  src/assets/scss/theme/light.scss
  src/assets/scss/theme/night.scss
  src/components/MsgLeftItem.vue
  src/components/MsgRightItem.vue
  src/database/database.config.ts
  src/database/migration/1688042450818-supportSchemas.ts
  src/database/migration/1688449795669-saveScriptName.ts
  src/database/models/MessageEntity.ts
  src/database/models/ScriptEntity.ts
  src/lang/connections.ts
  src/types/global.d.ts
  src/utils/element.ts
  src/views/connections/ConnectionsDetail.vue
Labels: feature, Desktop

#1345 style(script):add script-output bottom padding
  src/views/script/index.vue
Labels: fix, Desktop

#1346 fix(script):function script error handling
  src/utils/sandbox.ts
  src/views/connections/ConnectionsDetail.vue
  src/views/script/index.vue
Labels: fix, Desktop

#1347 fix(connections): completed i18n
  src/lang/connections.ts
Labels: fix, Desktop

#1348 chore(script):modify some script example
  scripts-example/function/dynamicSwitch.js
  scripts-example/function/tempAndHum.js
  scripts-example/function/timestamp.js
  scripts-example/schema/Person.proto
  src/lang/connections.ts
  src/views/connections/ConnectionsDetail.vue
Labels: docs

#1349 style(message): modify the message max width
  src/assets/scss/mixins.scss
  web/src/assets/scss/mixins.scss
Labels: fix, UI \ UX

#1350 fix(connection):fix vaild-format-json error
  src/components/MsgPublish.vue
  src/utils/validFormatJson.ts
  src/views/connections/ConnectionsDetail.vue
Labels: fix, Desktop

#1352 chore(cli):add js-yaml types
  cli/package.json
  cli/yarn.lock
Labels: fix, CLI

#1359 fix(connections):fix text processing error
  src/views/connections/ConnectionsDetail.vue
Labels: fix, desktop

#1353 feat(ci): upload packages to aws s3
  .github/workflows/build_cli.yaml
  .github/workflows/build_packages.yaml
  .github/workflows/deploy_web.yaml
Labels: chore

#1374 chore(ci): add node version
  .github/workflows/build_packages.yaml
Labels: chore

#1377 improve(upodate):lazy update detection and component loading
  src/main/updateChecker.ts
  src/main/updateDownloader.ts
  src/views/Home.vue
Labels: fix, desktop

#1379 fix(connections-detail):use event listeners instead of onsize events
  src/views/connections/ConnectionsDetail.vue
  src/views/update/index.vue
Labels: fix, desktop

#1378 style(subscriptions-list):modify scrollbar style
  src/assets/scss/base.scss
  src/components/SubscriptionsList.vue
Labels: fix, desktop

#1380 style(key-value-editor):modify el-input styles
  src/components/KeyValueEditor.vue
  src/components/MsgLeftItem.vue
  src/components/MsgRightItem.vue
Labels: fix, desktop
