Repository emqx/MQTTX, pull requests merged in 2024-01, with the labels that each got.

#1546 docs(readme): update badges
  README.md
Labels: enhancement, docs

#1550 feat(web): add disconnect event
  web/src/lang/connections.ts
  web/src/views/connections/ConnectionsDetail.vue
Labels: enhancement, feature, web

#1551 feat(cli): add disconnect event
  cli/src/lib/conn.ts
  cli/src/lib/pub.ts
  cli/src/lib/sub.ts
  cli/src/utils/signale.ts
Labels: enhancement, feature, CLI

#1559 docs(readme): simplify cli readme
  cli/README.md
  web/README.md
Labels: docs, CLI, web

#1560 fix(connection): the reconnect can only works on current page
  src/views/connections/ConnectionsDetail.vue
Labels: enhancement, fix, desktop

#1547 feat(decoder): added CBOR as new option data type to decode the paylo…
  package.json
  src/database/models/HistoryMessagePayloadEntity.ts
  src/types/global.d.ts
  src/views/connections/ConnectionsDetail.vue
  yarn.lock
Labels: enhancement, feature, desktop

#1562 refactor(msg): payload type table migration and update
  package.json
  src/components/MsgLeftItem.vue
  src/components/MsgPublish.vue
  src/database/database.config.ts
  src/database/migration/1705478422620-updatePayloadTypeToVarchar.ts
  src/database/models/HistoryMessagePayloadEntity.ts
  src/types/global.d.ts
  src/views/connections/ConnectionsDetail.vue
Labels: enhancement, migration, desktop

#1564 style(convertPayload.ts): adding formatting text on publish field whe…
  src/utils/convertPayload.ts
Labels: enhancement, desktop

#1565 feat(cli): cbor format support
  cli/package.json
  cli/src/index.ts
  cli/src/lib/pub.ts
  cli/src/lib/sub.ts
  cli/src/types/global.d.ts
  cli/src/utils/convertPayload.ts
  cli/src/utils/parse.ts
  cli/yarn.lock
Labels: feature, CLI

#1569 refactor(desktop): extracted hard-coded style values into enums
  src/components/EmptyPage.vue
  src/components/SubscriptionsList.vue
  src/utils/styles.ts
  src/views/connections/ConnectionForm.vue
  src/views/connections/ConnectionsDetail.vue
Labels: enhancement, refactor, desktop

#1570 fix(desltop): fix editor layout issue when conn-list visible change
  src/components/Editor.vue
Labels: fix, desktop

#1571 feat(cli): add message limit option to bench pub command
  cli/src/index.ts
  cli/src/lib/pub.ts
  cli/src/types/global.d.ts
Labels: feature, CLI

#1574 refactor(desktop): all icons updated
  src/assets/font/iconfont.css
  src/assets/font/iconfont.js
  src/assets/font/iconfont.json
  src/assets/font/iconfont.ttf
  src/assets/font/iconfont.woff
  src/assets/font/iconfont.woff2
  src/components/Copilot.vue
  src/components/MsgPublish.vue
  src/components/UseScript.vue
  src/lang/connections.ts
  src/views/about/index.vue
  src/views/connections/ConnectionsDetail.vue
  src/views/connections/ConnectionsList.vue
  src/views/script/index.vue
Labels: enhancement, refactor, desktop

#1577 fix(desktop): fix can not hide the conn-list in new window
  src/assets/scss/connections.scss
  src/views/connections/index.vue
  src/views/window/Window.vue
Labels: fix, desktop
