Repository emqx/MQTTX, pull requests merged in 2024-10, with the labels that each got.

#1782 fix(desktop): fix tooltip overflow in tree visual component
  src/components/charts/TreeVisual.vue
  src/components/widgets/TreeView.vue
Labels: fix, desktop

#1783 fix(desktop): fix can not init unread message count issue
  src/views/connections/ConnectionsList.vue
Labels: fix, desktop

#1784 fix(desktop): delay open the topic tooltip
  src/components/SubscriptionsList.vue
Labels: fix, desktop

#1785 fix(desktop): optimize scrollbar corner style in topic tree
  src/assets/scss/base.scss
  src/components/widgets/TreeNodeInfo.vue
Labels: fix, UI/UX, desktop

#1788 chore(deps): update turbo from 1.10.16 to 2.2.3
  package.json
  pnpm-lock.yaml
  turbo.json
Labels: dependencies, chore
