Repository emqx/MQTTX, pull requests merged in 2024-03, with the labels that each got.

#1600 feat(cli): add message limit option to simulate command
  cli/src/index.ts
Labels: feature, CLI

#1603 docs(readme): update readme
  README-CN.md
  README-JP.md
  README.md
  cli/README-CN.md
  cli/README.md
  web/README-CN.md
  web/README.md
Labels: docs

#1602 feat(desktop): remember the selected encode/decode type
  src/views/connections/ConnectionsDetail.vue
Labels: enhancement, feature, desktop

#1608 1.9.10
  cli/package.json
  package.json
  src/version.ts
  web/package.json
Labels: upgrade

#1612 feat(assets): add save icon
  src/assets/font/iconfont.css
  src/assets/font/iconfont.js
  src/assets/font/iconfont.json
  src/assets/font/iconfont.ttf
  src/assets/font/iconfont.woff
  src/assets/font/iconfont.woff2
  src/lang/common.ts
  src/views/connections/ConnectionForm.vue
  web/src/assets/font/iconfont.css
  web/src/assets/font/iconfont.js
  web/src/assets/font/iconfont.json
  web/src/assets/font/iconfont.ttf
  web/src/assets/font/iconfont.woff
  web/src/assets/font/iconfont.woff2
  web/src/lang/common.ts
  web/src/views/connections/ConnectionForm.vue
Labels: enhancement, UI/UX, web, desktop
