Repository emqx/MQTTX, pull requests merged in 2024-11, with the labels that each got.

#1795 feat(desktop): traffic rate monitor support
  src/components/charts/LineChartExtent.vue
  src/components/charts/NumberCard.vue
  src/lang/viewer.ts
  src/types/global.d.ts
  src/utils/formatter.ts
  src/utils/systemTopic.ts
  src/views/viewer/TopicTree.vue
  src/views/viewer/TrafficMonitor.vue
  src/widgets/TrafficStatistics.vue
  src/widgets/TreeNodeInfo.vue
  src/widgets/TreeView.vue
  tests/unit/utils/formatter.spec.ts
  tests/unit/utils/systemTopic.spec.ts
Labels: enhancement, feature, desktop

#1796 feat(desktop): traffic rate monitor support
  src/assets/scss/element/element-reset.scss
  src/components/TimeRangeSelect.vue
  src/lang/common.ts
  src/lang/viewer.ts
  src/utils/element.ts
  src/views/viewer/TrafficMonitor.vue
Labels: enhancement, feature, desktop

#1801 fix(cli): move @faker-js/faker to dependencies
  cli/package.json
Labels: dependencies, discussion, chore, CLI

#1808 fix(cli): support more biarny type files
  cli/src/__tests__/utils/binaryFormats.test.ts
  cli/src/utils/binaryFormats.ts
Labels: enhancement, fix, CLI

#1817 refactor(desktop): add mqtt properties component
  src/components/MqttProperties.vue
  src/components/MsgLeftItem.vue
  src/components/MsgRightItem.vue
Labels: enhancement, desktop

#1819 refactor(desktop): add mqtt properties component
  src/components/MqttProperties.vue
  src/widgets/TreeNodeInfo.vue
Labels: enhancement, feature, desktop
