Repository emqx/MQTTX, pull requests merged in 2024-07, with the labels that each got.

#1709 fix(desktop): support show load data errors
  src/views/connections/index.vue
Labels: enhancement, fix, desktop

#1710 docs(web): update online usage link
  web/README-CN.md
  web/README.md
Labels: docs, web

#1711 fix(desktop): support rebuild database when load connection error
  src/background.ts
  src/components/DatabaseError.vue
  src/database/rebuildDatabase.ts
  src/store/modules/app.ts
  src/views/connections/index.vue
Labels: fix, migration, desktop

#1717 chore(ci): remove cr
  .github/workflows/cr.yaml
Labels: CI/CD

#1719 fix(cli): code format
  cli/src/index.ts
Labels: fix, CLI

#1718 feat(desktop): skip cli version check on windows
  src/main/installCLI.ts
Labels: enhancement, desktop

#1720 1.10.1
  cli/package.json
  package.json
  src/version.ts
  web/package.json
Labels: upgrade

#1724 fix(desktop): fix the style issue of connection name
  src/views/connections/ConnectionsDetail.vue
  web/src/views/connections/ConnectionsDetail.vue
Labels: bug, UI/UX, web, desktop

#1729 feat(cli): custom ws headers support
  cli/src/index.ts
  cli/src/types/global.d.ts
  cli/src/utils/parse.ts
Labels: enhancement, feature, CLI
