Repository emqx/MQTTX, pull requests merged in 2025-09, with the labels that each got.

#1980 fix(KeyValueEditor.vue): fix a User Property display bug in Topics Tree
  src/components/KeyValueEditor.vue
Labels: fix, desktop

#1981 fix: adjust history navigation button layout to prevent right arrow f…
  src/components/MsgPublish.vue
Labels: fix, UI/UX, desktop

#1983 feat(desktop): implement SCRAM enhanced authentication for MQTT 5.0
  package.json
  src/lang/connections.ts
  src/utils/mqttUtils.ts
  src/utils/scramAuth.ts
  src/utils/scramUtils.ts
  src/views/connections/ConnectionForm.vue
  tests/unit/utils/scramAuth.spec.ts
  tests/unit/utils/scramUtils.spec.ts
  yarn.lock
Labels: enhancement, feature, desktop
