Repository emqx/MQTTX, pull requests merged in 2025-08, with the labels that each got.

#1964 fix(MsgItem): correct highlight logic to handle payload when no search params
  src/components/MsgLeftItem.vue
  src/components/MsgRightItem.vue
  src/utils/highlightSearch.ts
Labels: enhancement, fix, desktop

#1974 fix(build): update Linux app icon to 512x512 resolution
  public/icons/512x512.png
  vue.config.js
Labels: fix, desktop, Linux

#1976 fix(desktop): unify app data path handling to fix Windows %APPDATA% redirect issue
  src/background.ts
  src/database/database.config.ts
  src/main/appDataPath.ts
  src/main/installCLI.ts
Labels: fix, desktop, Windows
